package com.z.flinkStreamOptimizatiion.test;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sliceActVV.proto

public final class SliceActVV {
  private SliceActVV() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface userInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:userInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rt_u_click = 1;</code>
     */
    long getRtUClick();

    /**
     * <code>int64 rt_u_reveal = 2;</code>
     */
    long getRtUReveal();

    /**
     * <code>double rt_u_rpt = 3;</code>
     */
    double getRtURpt();
  }
  /**
   * Protobuf type {@code userInfo}
   */
  public  static final class userInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:userInfo)
      userInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use userInfo.newBuilder() to construct.
    private userInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private userInfo() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private userInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rtUClick_ = input.readInt64();
              break;
            }
            case 16: {

              rtUReveal_ = input.readInt64();
              break;
            }
            case 25: {

              rtURpt_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SliceActVV.internal_static_userInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SliceActVV.internal_static_userInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              userInfo.class, Builder.class);
    }

    public static final int RT_U_CLICK_FIELD_NUMBER = 1;
    private long rtUClick_;
    /**
     * <code>int64 rt_u_click = 1;</code>
     */
    public long getRtUClick() {
      return rtUClick_;
    }

    public static final int RT_U_REVEAL_FIELD_NUMBER = 2;
    private long rtUReveal_;
    /**
     * <code>int64 rt_u_reveal = 2;</code>
     */
    public long getRtUReveal() {
      return rtUReveal_;
    }

    public static final int RT_U_RPT_FIELD_NUMBER = 3;
    private double rtURpt_;
    /**
     * <code>double rt_u_rpt = 3;</code>
     */
    public double getRtURpt() {
      return rtURpt_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rtUClick_ != 0L) {
        output.writeInt64(1, rtUClick_);
      }
      if (rtUReveal_ != 0L) {
        output.writeInt64(2, rtUReveal_);
      }
      if (rtURpt_ != 0D) {
        output.writeDouble(3, rtURpt_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rtUClick_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rtUClick_);
      }
      if (rtUReveal_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, rtUReveal_);
      }
      if (rtURpt_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, rtURpt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof userInfo)) {
        return super.equals(obj);
      }
      userInfo other = (userInfo) obj;

      if (getRtUClick()
          != other.getRtUClick()) return false;
      if (getRtUReveal()
          != other.getRtUReveal()) return false;
      if (Double.doubleToLongBits(getRtURpt())
          != Double.doubleToLongBits(
              other.getRtURpt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RT_U_CLICK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtUClick());
      hash = (37 * hash) + RT_U_REVEAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtUReveal());
      hash = (37 * hash) + RT_U_RPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRtURpt()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static userInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static userInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static userInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static userInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static userInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static userInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static userInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static userInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static userInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static userInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static userInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static userInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(userInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code userInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:userInfo)
        userInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SliceActVV.internal_static_userInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SliceActVV.internal_static_userInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                userInfo.class, Builder.class);
      }

      // Construct using SliceActVV.userInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rtUClick_ = 0L;

        rtUReveal_ = 0L;

        rtURpt_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SliceActVV.internal_static_userInfo_descriptor;
      }

      @Override
      public userInfo getDefaultInstanceForType() {
        return userInfo.getDefaultInstance();
      }

      @Override
      public userInfo build() {
        userInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public userInfo buildPartial() {
        userInfo result = new userInfo(this);
        result.rtUClick_ = rtUClick_;
        result.rtUReveal_ = rtUReveal_;
        result.rtURpt_ = rtURpt_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof userInfo) {
          return mergeFrom((userInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(userInfo other) {
        if (other == userInfo.getDefaultInstance()) return this;
        if (other.getRtUClick() != 0L) {
          setRtUClick(other.getRtUClick());
        }
        if (other.getRtUReveal() != 0L) {
          setRtUReveal(other.getRtUReveal());
        }
        if (other.getRtURpt() != 0D) {
          setRtURpt(other.getRtURpt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        userInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (userInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long rtUClick_ ;
      /**
       * <code>int64 rt_u_click = 1;</code>
       */
      public long getRtUClick() {
        return rtUClick_;
      }
      /**
       * <code>int64 rt_u_click = 1;</code>
       */
      public Builder setRtUClick(long value) {
        
        rtUClick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_u_click = 1;</code>
       */
      public Builder clearRtUClick() {
        
        rtUClick_ = 0L;
        onChanged();
        return this;
      }

      private long rtUReveal_ ;
      /**
       * <code>int64 rt_u_reveal = 2;</code>
       */
      public long getRtUReveal() {
        return rtUReveal_;
      }
      /**
       * <code>int64 rt_u_reveal = 2;</code>
       */
      public Builder setRtUReveal(long value) {
        
        rtUReveal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_u_reveal = 2;</code>
       */
      public Builder clearRtUReveal() {
        
        rtUReveal_ = 0L;
        onChanged();
        return this;
      }

      private double rtURpt_ ;
      /**
       * <code>double rt_u_rpt = 3;</code>
       */
      public double getRtURpt() {
        return rtURpt_;
      }
      /**
       * <code>double rt_u_rpt = 3;</code>
       */
      public Builder setRtURpt(double value) {
        
        rtURpt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rt_u_rpt = 3;</code>
       */
      public Builder clearRtURpt() {
        
        rtURpt_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:userInfo)
    }

    // @@protoc_insertion_point(class_scope:userInfo)
    private static final userInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new userInfo();
    }

    public static userInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<userInfo>
        PARSER = new com.google.protobuf.AbstractParser<userInfo>() {
      @Override
      public userInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new userInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<userInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<userInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public userInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface feedInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:feedInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rt_f_click = 1;</code>
     */
    long getRtFClick();

    /**
     * <code>int64 rt_f_reveal = 2;</code>
     */
    long getRtFReveal();

    /**
     * <code>double rt_f_rpt = 3;</code>
     */
    double getRtFRpt();

    /**
     * <code>int64 rt_f_2h_click = 4;</code>
     */
    long getRtF2HClick();

    /**
     * <code>int64 rt_f_2h_reveal = 5;</code>
     */
    long getRtF2HReveal();

    /**
     * <code>double rt_f_2h_rpt = 6;</code>
     */
    double getRtF2HRpt();

    /**
     * <code>int64 rt_f_4h_click = 7;</code>
     */
    long getRtF4HClick();

    /**
     * <code>int64 rt_f_4h_reveal = 8;</code>
     */
    long getRtF4HReveal();

    /**
     * <code>double rt_f_4h_rpt = 9;</code>
     */
    double getRtF4HRpt();
  }
  /**
   * Protobuf type {@code feedInfo}
   */
  public  static final class feedInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:feedInfo)
      feedInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use feedInfo.newBuilder() to construct.
    private feedInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private feedInfo() {
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private feedInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rtFClick_ = input.readInt64();
              break;
            }
            case 16: {

              rtFReveal_ = input.readInt64();
              break;
            }
            case 25: {

              rtFRpt_ = input.readDouble();
              break;
            }
            case 32: {

              rtF2HClick_ = input.readInt64();
              break;
            }
            case 40: {

              rtF2HReveal_ = input.readInt64();
              break;
            }
            case 49: {

              rtF2HRpt_ = input.readDouble();
              break;
            }
            case 56: {

              rtF4HClick_ = input.readInt64();
              break;
            }
            case 64: {

              rtF4HReveal_ = input.readInt64();
              break;
            }
            case 73: {

              rtF4HRpt_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SliceActVV.internal_static_feedInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SliceActVV.internal_static_feedInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              feedInfo.class, Builder.class);
    }

    public static final int RT_F_CLICK_FIELD_NUMBER = 1;
    private long rtFClick_;
    /**
     * <code>int64 rt_f_click = 1;</code>
     */
    public long getRtFClick() {
      return rtFClick_;
    }

    public static final int RT_F_REVEAL_FIELD_NUMBER = 2;
    private long rtFReveal_;
    /**
     * <code>int64 rt_f_reveal = 2;</code>
     */
    public long getRtFReveal() {
      return rtFReveal_;
    }

    public static final int RT_F_RPT_FIELD_NUMBER = 3;
    private double rtFRpt_;
    /**
     * <code>double rt_f_rpt = 3;</code>
     */
    public double getRtFRpt() {
      return rtFRpt_;
    }

    public static final int RT_F_2H_CLICK_FIELD_NUMBER = 4;
    private long rtF2HClick_;
    /**
     * <code>int64 rt_f_2h_click = 4;</code>
     */
    public long getRtF2HClick() {
      return rtF2HClick_;
    }

    public static final int RT_F_2H_REVEAL_FIELD_NUMBER = 5;
    private long rtF2HReveal_;
    /**
     * <code>int64 rt_f_2h_reveal = 5;</code>
     */
    public long getRtF2HReveal() {
      return rtF2HReveal_;
    }

    public static final int RT_F_2H_RPT_FIELD_NUMBER = 6;
    private double rtF2HRpt_;
    /**
     * <code>double rt_f_2h_rpt = 6;</code>
     */
    public double getRtF2HRpt() {
      return rtF2HRpt_;
    }

    public static final int RT_F_4H_CLICK_FIELD_NUMBER = 7;
    private long rtF4HClick_;
    /**
     * <code>int64 rt_f_4h_click = 7;</code>
     */
    public long getRtF4HClick() {
      return rtF4HClick_;
    }

    public static final int RT_F_4H_REVEAL_FIELD_NUMBER = 8;
    private long rtF4HReveal_;
    /**
     * <code>int64 rt_f_4h_reveal = 8;</code>
     */
    public long getRtF4HReveal() {
      return rtF4HReveal_;
    }

    public static final int RT_F_4H_RPT_FIELD_NUMBER = 9;
    private double rtF4HRpt_;
    /**
     * <code>double rt_f_4h_rpt = 9;</code>
     */
    public double getRtF4HRpt() {
      return rtF4HRpt_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rtFClick_ != 0L) {
        output.writeInt64(1, rtFClick_);
      }
      if (rtFReveal_ != 0L) {
        output.writeInt64(2, rtFReveal_);
      }
      if (rtFRpt_ != 0D) {
        output.writeDouble(3, rtFRpt_);
      }
      if (rtF2HClick_ != 0L) {
        output.writeInt64(4, rtF2HClick_);
      }
      if (rtF2HReveal_ != 0L) {
        output.writeInt64(5, rtF2HReveal_);
      }
      if (rtF2HRpt_ != 0D) {
        output.writeDouble(6, rtF2HRpt_);
      }
      if (rtF4HClick_ != 0L) {
        output.writeInt64(7, rtF4HClick_);
      }
      if (rtF4HReveal_ != 0L) {
        output.writeInt64(8, rtF4HReveal_);
      }
      if (rtF4HRpt_ != 0D) {
        output.writeDouble(9, rtF4HRpt_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rtFClick_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rtFClick_);
      }
      if (rtFReveal_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, rtFReveal_);
      }
      if (rtFRpt_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, rtFRpt_);
      }
      if (rtF2HClick_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, rtF2HClick_);
      }
      if (rtF2HReveal_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, rtF2HReveal_);
      }
      if (rtF2HRpt_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, rtF2HRpt_);
      }
      if (rtF4HClick_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, rtF4HClick_);
      }
      if (rtF4HReveal_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, rtF4HReveal_);
      }
      if (rtF4HRpt_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, rtF4HRpt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof feedInfo)) {
        return super.equals(obj);
      }
      feedInfo other = (feedInfo) obj;

      if (getRtFClick()
          != other.getRtFClick()) return false;
      if (getRtFReveal()
          != other.getRtFReveal()) return false;
      if (Double.doubleToLongBits(getRtFRpt())
          != Double.doubleToLongBits(
              other.getRtFRpt())) return false;
      if (getRtF2HClick()
          != other.getRtF2HClick()) return false;
      if (getRtF2HReveal()
          != other.getRtF2HReveal()) return false;
      if (Double.doubleToLongBits(getRtF2HRpt())
          != Double.doubleToLongBits(
              other.getRtF2HRpt())) return false;
      if (getRtF4HClick()
          != other.getRtF4HClick()) return false;
      if (getRtF4HReveal()
          != other.getRtF4HReveal()) return false;
      if (Double.doubleToLongBits(getRtF4HRpt())
          != Double.doubleToLongBits(
              other.getRtF4HRpt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RT_F_CLICK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtFClick());
      hash = (37 * hash) + RT_F_REVEAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtFReveal());
      hash = (37 * hash) + RT_F_RPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRtFRpt()));
      hash = (37 * hash) + RT_F_2H_CLICK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtF2HClick());
      hash = (37 * hash) + RT_F_2H_REVEAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtF2HReveal());
      hash = (37 * hash) + RT_F_2H_RPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRtF2HRpt()));
      hash = (37 * hash) + RT_F_4H_CLICK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtF4HClick());
      hash = (37 * hash) + RT_F_4H_REVEAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRtF4HReveal());
      hash = (37 * hash) + RT_F_4H_RPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getRtF4HRpt()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static feedInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feedInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feedInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feedInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feedInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static feedInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static feedInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feedInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static feedInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static feedInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static feedInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static feedInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(feedInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code feedInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:feedInfo)
        feedInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SliceActVV.internal_static_feedInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SliceActVV.internal_static_feedInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                feedInfo.class, Builder.class);
      }

      // Construct using SliceActVV.feedInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rtFClick_ = 0L;

        rtFReveal_ = 0L;

        rtFRpt_ = 0D;

        rtF2HClick_ = 0L;

        rtF2HReveal_ = 0L;

        rtF2HRpt_ = 0D;

        rtF4HClick_ = 0L;

        rtF4HReveal_ = 0L;

        rtF4HRpt_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SliceActVV.internal_static_feedInfo_descriptor;
      }

      @Override
      public feedInfo getDefaultInstanceForType() {
        return feedInfo.getDefaultInstance();
      }

      @Override
      public feedInfo build() {
        feedInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public feedInfo buildPartial() {
        feedInfo result = new feedInfo(this);
        result.rtFClick_ = rtFClick_;
        result.rtFReveal_ = rtFReveal_;
        result.rtFRpt_ = rtFRpt_;
        result.rtF2HClick_ = rtF2HClick_;
        result.rtF2HReveal_ = rtF2HReveal_;
        result.rtF2HRpt_ = rtF2HRpt_;
        result.rtF4HClick_ = rtF4HClick_;
        result.rtF4HReveal_ = rtF4HReveal_;
        result.rtF4HRpt_ = rtF4HRpt_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof feedInfo) {
          return mergeFrom((feedInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(feedInfo other) {
        if (other == feedInfo.getDefaultInstance()) return this;
        if (other.getRtFClick() != 0L) {
          setRtFClick(other.getRtFClick());
        }
        if (other.getRtFReveal() != 0L) {
          setRtFReveal(other.getRtFReveal());
        }
        if (other.getRtFRpt() != 0D) {
          setRtFRpt(other.getRtFRpt());
        }
        if (other.getRtF2HClick() != 0L) {
          setRtF2HClick(other.getRtF2HClick());
        }
        if (other.getRtF2HReveal() != 0L) {
          setRtF2HReveal(other.getRtF2HReveal());
        }
        if (other.getRtF2HRpt() != 0D) {
          setRtF2HRpt(other.getRtF2HRpt());
        }
        if (other.getRtF4HClick() != 0L) {
          setRtF4HClick(other.getRtF4HClick());
        }
        if (other.getRtF4HReveal() != 0L) {
          setRtF4HReveal(other.getRtF4HReveal());
        }
        if (other.getRtF4HRpt() != 0D) {
          setRtF4HRpt(other.getRtF4HRpt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        feedInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (feedInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long rtFClick_ ;
      /**
       * <code>int64 rt_f_click = 1;</code>
       */
      public long getRtFClick() {
        return rtFClick_;
      }
      /**
       * <code>int64 rt_f_click = 1;</code>
       */
      public Builder setRtFClick(long value) {
        
        rtFClick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_f_click = 1;</code>
       */
      public Builder clearRtFClick() {
        
        rtFClick_ = 0L;
        onChanged();
        return this;
      }

      private long rtFReveal_ ;
      /**
       * <code>int64 rt_f_reveal = 2;</code>
       */
      public long getRtFReveal() {
        return rtFReveal_;
      }
      /**
       * <code>int64 rt_f_reveal = 2;</code>
       */
      public Builder setRtFReveal(long value) {
        
        rtFReveal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_f_reveal = 2;</code>
       */
      public Builder clearRtFReveal() {
        
        rtFReveal_ = 0L;
        onChanged();
        return this;
      }

      private double rtFRpt_ ;
      /**
       * <code>double rt_f_rpt = 3;</code>
       */
      public double getRtFRpt() {
        return rtFRpt_;
      }
      /**
       * <code>double rt_f_rpt = 3;</code>
       */
      public Builder setRtFRpt(double value) {
        
        rtFRpt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rt_f_rpt = 3;</code>
       */
      public Builder clearRtFRpt() {
        
        rtFRpt_ = 0D;
        onChanged();
        return this;
      }

      private long rtF2HClick_ ;
      /**
       * <code>int64 rt_f_2h_click = 4;</code>
       */
      public long getRtF2HClick() {
        return rtF2HClick_;
      }
      /**
       * <code>int64 rt_f_2h_click = 4;</code>
       */
      public Builder setRtF2HClick(long value) {
        
        rtF2HClick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_f_2h_click = 4;</code>
       */
      public Builder clearRtF2HClick() {
        
        rtF2HClick_ = 0L;
        onChanged();
        return this;
      }

      private long rtF2HReveal_ ;
      /**
       * <code>int64 rt_f_2h_reveal = 5;</code>
       */
      public long getRtF2HReveal() {
        return rtF2HReveal_;
      }
      /**
       * <code>int64 rt_f_2h_reveal = 5;</code>
       */
      public Builder setRtF2HReveal(long value) {
        
        rtF2HReveal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_f_2h_reveal = 5;</code>
       */
      public Builder clearRtF2HReveal() {
        
        rtF2HReveal_ = 0L;
        onChanged();
        return this;
      }

      private double rtF2HRpt_ ;
      /**
       * <code>double rt_f_2h_rpt = 6;</code>
       */
      public double getRtF2HRpt() {
        return rtF2HRpt_;
      }
      /**
       * <code>double rt_f_2h_rpt = 6;</code>
       */
      public Builder setRtF2HRpt(double value) {
        
        rtF2HRpt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rt_f_2h_rpt = 6;</code>
       */
      public Builder clearRtF2HRpt() {
        
        rtF2HRpt_ = 0D;
        onChanged();
        return this;
      }

      private long rtF4HClick_ ;
      /**
       * <code>int64 rt_f_4h_click = 7;</code>
       */
      public long getRtF4HClick() {
        return rtF4HClick_;
      }
      /**
       * <code>int64 rt_f_4h_click = 7;</code>
       */
      public Builder setRtF4HClick(long value) {
        
        rtF4HClick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_f_4h_click = 7;</code>
       */
      public Builder clearRtF4HClick() {
        
        rtF4HClick_ = 0L;
        onChanged();
        return this;
      }

      private long rtF4HReveal_ ;
      /**
       * <code>int64 rt_f_4h_reveal = 8;</code>
       */
      public long getRtF4HReveal() {
        return rtF4HReveal_;
      }
      /**
       * <code>int64 rt_f_4h_reveal = 8;</code>
       */
      public Builder setRtF4HReveal(long value) {
        
        rtF4HReveal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rt_f_4h_reveal = 8;</code>
       */
      public Builder clearRtF4HReveal() {
        
        rtF4HReveal_ = 0L;
        onChanged();
        return this;
      }

      private double rtF4HRpt_ ;
      /**
       * <code>double rt_f_4h_rpt = 9;</code>
       */
      public double getRtF4HRpt() {
        return rtF4HRpt_;
      }
      /**
       * <code>double rt_f_4h_rpt = 9;</code>
       */
      public Builder setRtF4HRpt(double value) {
        
        rtF4HRpt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rt_f_4h_rpt = 9;</code>
       */
      public Builder clearRtF4HRpt() {
        
        rtF4HRpt_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:feedInfo)
    }

    // @@protoc_insertion_point(class_scope:feedInfo)
    private static final feedInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new feedInfo();
    }

    public static feedInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<feedInfo>
        PARSER = new com.google.protobuf.AbstractParser<feedInfo>() {
      @Override
      public feedInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new feedInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<feedInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<feedInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public feedInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feedInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feedInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020sliceActVV.proto\"E\n\010userInfo\022\022\n\nrt_u_c" +
      "lick\030\001 \001(\003\022\023\n\013rt_u_reveal\030\002 \001(\003\022\020\n\010rt_u_" +
      "rpt\030\003 \001(\001\"\315\001\n\010feedInfo\022\022\n\nrt_f_click\030\001 \001" +
      "(\003\022\023\n\013rt_f_reveal\030\002 \001(\003\022\020\n\010rt_f_rpt\030\003 \001(" +
      "\001\022\025\n\rrt_f_2h_click\030\004 \001(\003\022\026\n\016rt_f_2h_reve" +
      "al\030\005 \001(\003\022\023\n\013rt_f_2h_rpt\030\006 \001(\001\022\025\n\rrt_f_4h" +
      "_click\030\007 \001(\003\022\026\n\016rt_f_4h_reveal\030\010 \001(\003\022\023\n\013" +
      "rt_f_4h_rpt\030\t \001(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_userInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userInfo_descriptor,
        new String[] { "RtUClick", "RtUReveal", "RtURpt", });
    internal_static_feedInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_feedInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feedInfo_descriptor,
        new String[] { "RtFClick", "RtFReveal", "RtFRpt", "RtF2HClick", "RtF2HReveal", "RtF2HRpt", "RtF4HClick", "RtF4HReveal", "RtF4HRpt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
